### ISSUE TITLE
Sitio de Tutoriales no funciona

### ISSUE THREAD

**Issue by Jzarecta** [eoscostarica/guias.eoscostarica.io#178]
**Describe the bug**
Al dar click en el boton de tutoriales me sale Page Not Found. 

**Expected behavior**
Ver el listado de tutorailes o esconder el boton a tutorailes. 

**Screenshots**
https://i.imgur.com/xIb4sHm.png

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Additional context**

**Comment by AngeloCG97** [comment]
Esta este botón debe llevar a esta sección 

![image](https://user-images.githubusercontent.com/51149817/104483571-e2473800-558d-11eb-99b1-00eda13a3d69.png)

**Comment by leisterfrancisco** [comment]
@Jzarecta this issue has been resolved, check it out at https://github.com/eoscostarica/guias.eoscostarica.io/pull/185, or well, go to the web page. Thanks for your report
