### ISSUE TITLE
Diseño de Página de inicio

### ISSUE THREAD

**Issue by JustinCast** [eoscostarica/guias.eoscostarica.io#21]
- [ ] Page Header 
- [ ] Visual Elements
- [ ] Descriptive paragraph  ( what and why? mission / objective )
- [ ] Medium Articles Section
- [ ] Twitter feed 
- [ ] Community Resources
- [ ] Tools
- [ ] Tutorials

**Comment by murillojorge** [comment]
I will include the Twitter and Medium components.

This is the latest design: https://zpl.io/bAogEm8

**Comment by xavier506** [comment]
https://zpl.io/aNgdEg4
