### ISSUE TITLE
Actualizar imagen para eosio dashboard

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guias.eoscostarica.io#218]
Actualicemos la imagen que tenemos en la  siguiente pagina por una mas nueva 

https://guias.eoscostarica.io/docs/proyectos-de-codigo-abierto#tablero-de-red-de-eosio

https://mainnet.eosio.cr

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/106047967-e2752680-60a9-11eb-8880-2cf777a158bd.png)

**Comment by Edgar097** [comment]
@leisterfrancisco can you give me an update of the images, from when you talked with Rodolfo please!
