### ISSUE TITLE
Agregar información sobre Full Stack Boilerplate

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guias.eoscostarica.io#220]
Crear una pagina nueva que describa la razón y los beneficios del una plantilla para iniciar un proyecto nuevo. 

enfoquémonos en el  repositorio full stack  pero incluyamos enlaces al  repo front end y backend . 

Fusionemos esta pagina nueva con los documentos pre-existentes 

https://guias.eoscostarica.io/docs/plantilla-para-aplicacion-web

https://guias.eoscostarica.io/docs/plantilla-para-backend

Related to : #205

**Comment by Edgar097** [comment]
Related to:
#183 
#230 
#231
Add links to this sections when they are done

**Comment by Edgar097** [comment]
@leisterfrancisco this is the first information of the boilerplate in es (FrontEnd).
Help me with suggestions
Also @xavier506 plz.
***
## ¿Qué es un Boilerplate?

Se le puede asociar a un framework o plantilla para el desarrollo de un proyecto. Es una estructura de soporte que ya esta definido por anteoridad que sirve para agilizar la organización y desarrollo de software. Integra soluciones y formatos que sirven para impulsar el desarrollo de un nuevo proyecto a producción.

Se divira el boilerplate en dos secciones para poder dividir el proyecto en FrontEnd sus tecnologías utilizadas y el BackEnd.

## Front End

### Features

This boilerplate features all the latest tools and practices in the industry.

- React.js - React 16✨, React Router 5
- Rematch/core - Rematch a Redux Framework
- Material-ui/core - React components for faster and easier web development
universal-authenticator-library - A library for allowing apps to easily use different auth providers (optional)
- Lint - ESlint
- Styles - Material-UI Theme (customizable)

### Antes de Empezar

Esto lo necesitamos para empezar:

- [git](https://guias.eoscostarica.io/docs/tutoriales/guia-github#git-bash)
- [node.js](https://guias.eoscostarica.io/docs/tutoriales/tutorial-react#herramientas)
- [yarn](https://classic.yarnpkg.com/en/docs/install/#windows-stable)

### Instalación

**Pasos**:

1. Clonar el repo:

```shell
$ git clone --depth=1 https://github.com/eoscostarica/webapp-boilerplate.git <YOUR_PROJECT_NAME>
```

2. Moverse al directorio:

```shell
$ cd <YOUR_PROJECT_NAME>
```

3. Correr proyecto:

```shell
$ yarn start
```

> [**GitHub Boilerplate**](https://github.com/eoscostarica/webapp-boilerplate)

## Componentes de React de EOSCR

Una colección de componentes de React para EOSIO. Para más información sobre los componentes puede visitar [Componentes en EOS Costa Rica](https://guias.eoscostarica.io/docs/tutoriales/tutorial-react#componentes-en-eos-costa-rica)

[GitHub](https://github.com/eoscostarica/eoscr-components)
